# Generated by Django 3.2 on 2023-01-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QA',
            new_name='QA2',
        ),
    ]
